# Generated by Django 4.1.7 on 2023-02-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_movieorder_movie_orders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieorder",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
